server:
  port: 8083

logging:
  file:
    path: logs

spring:
  application:
    name: consumer
  rabbitmq:
    host: 106.14.119.197
    port: 5672
    virtual-host: /srw
    username: srw
    password: srw
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 10
        prefetch: 1
        retry:
          enabled: true