server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always

spring:
  profiles:
    include: business,persistence,common
  application:
    name: api
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 10
      max-active: 20
      max-wait: 10000
      min-idle: 8
      url: jdbc:mysql://db:3306/srw?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: reader
      password: 123456
  data:
    mongodb:
      host: mongo # mongodb的连接地址
      port: 27017 # mongodb的连接端口号
      database: srw # mongodb的连接的数据库
  redis:
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-idle: 8 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
        max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制
    host: redis
    port: 6379

zookeeper:
  connect-string: 106.14.119.197:2181
  timeout: 2000

logging:
  file:
    path: logs

